name: Hadolint


on:
  - push
  - pull_request


jobs:
  hadolint:

    runs-on: ubuntu-latest

    strategy:
        matrix:
          dockerfile: ["docker-builds/server/Dockerfile", "docker-builds/ui/Dockerfile"]

    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: ${{ matrix.dockerfile }}
