name: Node.js CI

on:
  push:
  pull_request:


jobs:
  nodejs-build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["11.14.x"]

    steps:
      - uses: actions/checkout@v2
      - name: Lint code using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g yarn
      - run: yarn deps
      - run: yarn lint
