
# name: Typo CI

# on:
#   pull_request:
#   push:
#     branches-ignore:
#       - master
# jobs:
#   spellcheck:
#     name: Typo CI (GitHub Action)
#     runs-on: ubuntu-latest
#     timeout-minutes: 4
#     steps:
#     - name: TypoCheck
#       uses: typoci/spellcheck-action@master
